name: Workflow One
on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, ready_for_review]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Run analysis
        run: echo "✅ CI analysis completed for this PR!" > result.txt

      - name: Upload analysis results
        uses: actions/upload-artifact@v4
        with:
          name: analysis-results
          path: result.txt
