name: Comment on PR
on:
  workflow_run:
    workflows: ["Workflow One"] # Runs only after Workflow One completes
    types:
      - completed

jobs:
  comment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Runs only if Workflow One was successful
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Artifact URL
        run: |
          ARTIFACT_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts" \
            | jq -r '.artifacts[] | select(.name=="analysis-results") | .archive_download_url')

          if [[ "$ARTIFACT_URL" == "null" ]]; then
            echo "❌ No artifact found. Exiting."
            exit 1
          fi

          echo "Downloading artifact from: $ARTIFACT_URL"
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o artifact.zip "$ARTIFACT_URL"
          unzip artifact.zip

      - name: Post a comment on PR
        run: |
          echo "📢 Commenting on PR:"
          echo $PR_URL
          cat result.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
